apisVersion: v1
kind: Service
metadata:
  labels:
    app: hellojenkins
  name: hellojenkins
spec:
  ports:
  - port: 9001
    protocol: TCP
    targetPort: 9001
  selector:
    app: hellojenkins
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hellojenkins
  name: hellojenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hellojenkins
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hellojenkins
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - image: rickyuby/hellojenkins
        name: hellojenkins
        ports:
        - containerPort: 9001






